#!/usr/bin/env python

import os

from jinja2 import Environment, FileSystemLoader, Template

fh_services = [
    {'name': 'fh-messaging', 'checks': ['ping', 'health'], 'hostgroups': ['core', 'mbaas']},
    {'name': 'fh-metrics', 'checks': ['ping', 'health'], 'hostgroups': ['core', 'mbaas']},
    {'name': 'fh-ngui', 'checks': ['ping', 'health'], 'hostgroups': ['core']},
    {'name': 'fh-supercore', 'checks': ['ping', 'health'], 'hostgroups': ['core']},
    {'name': 'fh-aaa', 'checks': ['ping', 'health'], 'hostgroups': ['core']},
    {'name': 'fh-appstore', 'checks': ['ping', 'health'], 'hostgroups': ['core']},
    {'name': 'fh-scm', 'checks': ['ping', 'health'], 'hostgroups': ['core']},
    {'name': 'fh-mbaas', 'checks': ['ping', 'health'], 'hostgroups': ['mbaas']},
    {'name': 'fh-statsd', 'checks': ['ping'], 'hostgroups': ['mbaas']},
    {'name': 'millicore', 'checks': ['health'], 'health_endpoint': '/box/api/health', 'hostgroups': ['core']},
    {'name': 'ups', 'checks': ['health'], 'health_endpoint': '/ag-push/rest/sys/info/health', 'hostgroups': ['core']}
]

rhmap_admin_email = os.getenv('RHMAP_ADMIN_EMAIL', 'root@localhost')
rhmap_router_dns = os.getenv('RHMAP_ROUTER_DNS', 'rhmap.localhost')
rhmap_hostgroups = os.getenv('RHMAP_HOSTGROUPS', 'core')

template_file = '/opt/rhmap/fhservices.cfg.j2'
nagios_config_filename = '/etc/nagios/conf.d/fhservices.cfg'

template_basename = os.path.basename(template_file)
template_dirname = os.path.dirname(template_file)

j2env = Environment(loader=FileSystemLoader(template_dirname), trim_blocks=True)
j2template = j2env.get_template(template_basename)

j2renderedouput = j2template.render(fh_services=fh_services,
                                    rhmap_hostgroups=rhmap_hostgroups,
                                    rhmap_router_dns=rhmap_router_dns,
                                    rhmap_admin_email=rhmap_admin_email)

with open(nagios_config_filename, 'wb') as nagios_config_file:
    nagios_config_file.write(j2renderedouput)
